### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-frontend#1203]
**Describe the bug**

The travis build is failing

It's related to this unit test
```
not ok 885 Chrome 67.0 - Acceptance | login: correct login at /login
    ---
        actual: >
            /login
        expected: >
            /
        stack: >
                at Object._callee2$ (http://localhost:7357/assets/tests.js:445:24)
                at tryCatch (http://localhost:7357/assets/vendor.js:11749:40)
                at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:11987:22)
                at Generator.prototype.(anonymous function) [as next] (http://localhost:7357/assets/vendor.js:11801:21)
                at step (http://localhost:7357/assets/tests.js:384:32)
                at http://localhost:7357/assets/tests.js:395:15
        Log: |
    ...
```

**Comment by Kreijstal** [comment]
It looks like it fails intermittently, that means, it fails sometimes, sometimes it passes, it can cause some trouble by pull requests when they don't pass

**Comment by niranjan94** [comment]
Seems to be resolved by https://github.com/fossasia/open-event-frontend/commit/f678cb17ebcaf33b7aa75c4497a89316a43ffeb3 

https://travis-ci.org/fossasia/open-event-frontend/builds/391272394
