### ISSUE TITLE
Site does not load on Chromium - Error messages in Console

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1486]
I am receiving a lot of errors in the console of next.eventyay.com. Chromium loads the page in Icognito mode. Firefox and Chrome also show console errors. Please see below.

```
ember-cli-live-reload.js:7 [Report Only] Refused to load the script 'http://next.eventyay.com:7020/livereload.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://*.googleapis.com https://maps.gstatic.com https://eventyay.com https://*.eventyay.com http://eventyay.local:65520 http://localhost:49153 www.google-analytics.com https://platform.twitter.com https://cdn.syndication.twimg.com http://127.0.0.1:5000 cdn.ravenjs.com localhost:7020 0.0.0.0:7020 undefined:7020".

(anonymous) @ ember-cli-live-reload.js:7
(index):476 [Report Only] Refused to connect to 'ws://next.eventyay.com:7020/livereload' because it violates the following Content Security Policy directive: "connect-src 'self' ws://eventyay.local:65520 ws://localhost:49153 https://maps.gstatic.com https://*.eventyay.com https://eventyay.com https://open-event-api-dev.herokuapp.com www.google-analytics.com http://127.0.0.1:5000 getsentry.com ws://localhost:7020 ws://0.0.0.0:7020 ws://undefined:7020 http://localhost:4200".

RequestIntercept.window.WebSocket @ (index):476
wysihtml-toolbar.min.js:5 Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHjx4wXg.woff2
l10n.js:769 l10n.js: Using forced locale: "en"
server.js:101 Passthrough request: GET /assets/locales/en.json
server.js:101 Passthrough request: GET http://api.eventyay.com/v1/settings
pretender.js:167 [Report Only] Refused to connect to 'http://api.eventyay.com/v1/settings' because it violates the following Content Security Policy directive: "connect-src 'self' ws://eventyay.local:65520 ws://localhost:49153 https://maps.gstatic.com https://*.eventyay.com https://eventyay.com https://open-event-api-dev.herokuapp.com www.google-analytics.com http://127.0.0.1:5000 getsentry.com ws://localhost:7020 ws://0.0.0.0:7020 ws://undefined:7020 http://localhost:4200".

send @ pretender.js:167
ember-console.js:29 Error while processing route: index Network request failed TypeError: Network request failed
    at FakeRequest.xhr.onerror (http://next.eventyay.com/assets/vendor.js:163423:16)
    at dispatchEvent (http://next.eventyay.com/assets/vendor.js:105428:36)
    at XMLHttpRequest.xhr.(anonymous function) (http://next.eventyay.com/assets/vendor.js:105436:9)
error @ ember-console.js:29
rsvp.js:27 Uncaught TypeError: Network request failed
    at FakeRequest.xhr.onerror (ember-fetch.js:459)
    at dispatchEvent (pretender.js:218)
    at XMLHttpRequest.xhr.(/anonymous function) (http://next.eventyay.com/assets/vendor.js:105436:9)
(index):1045 [Deprecation] Application Cache is deprecated in non-secure contexts, and will be restricted to secure contexts in M69, around September 2018. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://goo.gl/rStTGz for more details.
(anonymous) @ (index):1045
l10n.js:769 l10n.js: An error occurred loading locale "en": Error: Resource was not found.
_log @ l10n.js:769
rsvp.js:27 Uncaught NotFoundError
util.js:226 Google Maps JavaScript API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key
ax.j @ util.js:226
js?key=Sample Key&libraries=places:39 Google Maps JavaScript API error: InvalidKeyMapError
https://developers.google.com/maps/documentation/javascript/error-messages#invalid-map-key-error
_.Nb @ js?key=Sample Key&libraries=places:39
```

**Comment by CosmicCoder96** [comment]
Deployment is being refreshed.
