### ISSUE TITLE
FetchError: request to http://127.0.0.1:5000/v1/settings failed, reason: connect ECONNREFUSED 127.0.0.1:5000

### ISSUE THREAD

**Issue by imrrahul** [fossasia/open-event-frontend#1999]
**Describe the bug**
On using the command `ember serve`  in the project directory and ember is running at http://localhost:4200/ but I have got the following error on the browser on running the project.

`FetchError: request to http://127.0.0.1:5000/v1/settings failed, reason: connect ECONNREFUSED 127.0.0.1:5000
    at ClientRequest.<anonymous> (/home/rahul/Desktop/FOSSASIA/open-event-frontend/node_modules/node-fetch/lib/index.js:1393:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)`

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser chrome

**Additional context**
node 8.1.0
yarn 1.3

**Comment by CosmicCoder96** [comment]
Have you set up the server and are you able to access it at localhost:5000 ? This error indicates the frontend is not able to access the server, please ask for further guidance on gitter channels, thank you !
