### ISSUE TITLE
"An unexpected error has occurred" on successful login.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2179]
**Describe the bug**

When the user logs in by providing the credentials, no redirect to home page happens and the url stays `http://localhost:4200/login` due to which error occurs.

**To Reproduce**
1. Go to 'login page'
2. Enter credentials and log in.
3. An unexpected error occurs

**Expected behavior**

The user should be redirected to home page.
**Screenshots**

![screenshot from 2019-02-10 11-04-57](https://user-images.githubusercontent.com/21174572/52530040-5040b000-2d24-11e9-9480-6de18c1e72dd.png)

**Additional context**

I am working on this issue.

**Comment by CosmicCoder96** [comment]
@Anupam-dagar can you share the exact error message from the dev console? Can't reproduce it.

**Comment by Anupam-dagar** [comment]
The error seems to be related to CORS. I have an extension enabled for it but still its there.
![screenshot from 2019-02-10 14-10-32](https://user-images.githubusercontent.com/21174572/52531725-dfa78c80-2d3f-11e9-879f-a30aef4862bf.png)

**Comment by uds5501** [comment]
@Anupam-dagar what kind of user were you trying to login with? The Admin / A new registered one?

**Comment by Anupam-dagar** [comment]
It's the admin user.

**Comment by CosmicCoder96** [comment]
It looks like a server error. What’s the stack trace there ?

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 Below is the stack trace on the server. so it says the orders.company doesn't exist.
```
127.0.0.1 - - [10/Feb/2019 16:08:56] "OPTIONS /auth/session HTTP/1.1" 200 -
127.0.0.1 - - [10/Feb/2019 16:08:56] "POST /auth/session HTTP/1.1" 200 -
127.0.0.1 - - [10/Feb/2019 16:08:56] "OPTIONS /v1/users/1 HTTP/1.1" 200 -
127.0.0.1 - - [10/Feb/2019 16:08:56] "OPTIONS /v1/events?filter=%5B%7B%22name%22%3A%22state%22%2C%22op%22%3A%22eq%22%2C%22val%22%3A%22published%22%7D%2C%7B%22or%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222019-02-10T10%3A38%3A56.422Z%22%7D%2C%7B%22name%22%3A%22ends-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222019-02-10T10%3A38%3A56.422Z%22%7D%5D%7D%5D&include=event-topic%2Cevent-sub-topic%2Cevent-type%2Cspeakers-call&page%5Bnumber%5D=1&page%5Bsize%5D=6&sort=starts-at HTTP/1.1" 200 -
127.0.0.1 - - [10/Feb/2019 16:08:56] "GET /v1/users/1 HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [10/Feb/2019 16:08:56] "GET /v1/users/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/anupam/github/open-event-server/app/__init__.py", line 67, in __call__
    return self.app(environ, start_response)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/home/anupam/github/open-event-server/app/api/helpers/permission_manager.py", line 439, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/home/anupam/github/open-event-server/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/home/anupam/github/open-event-server/app/api/helpers/permission_manager.py", line 112, in is_user_itself
    return view(*view_args, **view_kwargs)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 248, in get
    result = schema.dump(obj).data
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 511, in dump
    **kwargs
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 147, in serialize
    index=(index if index_errors else None)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 141, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 243, in serialize
    value = self.get_value(attr, obj, accessor=accessor)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 186, in get_value
    return accessor_func(check_key, obj, default)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 402, in get_attribute
    return utils.get_value(attr, obj, default)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/utils.py", line 306, in get_value
    return _get_value_for_keys(key.split('.'), obj, default)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/utils.py", line 311, in _get_value_for_keys
    return _get_value_for_key(keys[0], obj, default)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/utils.py", line 322, in _get_value_for_key
    attr = getattr(obj, key)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 557, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
    
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 635, in _emit_lazyload
    result = q.all()
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column orders.company does not exist
LINE 1: ...orders_country, orders.zipcode AS orders_zipcode, orders.com...
                                                             ^
 [SQL: 'SELECT orders.deleted_at AS orders_deleted_at, orders.id AS orders_id, orders.identifier AS orders_identifier, orders.amount AS orders_amount, orders.address AS orders_address, orders.city AS orders_city, orders.state AS orders_state, orders.country AS orders_country, orders.zipcode AS orders_zipcode, orders.company AS orders_company, orders.tax_business_info AS orders_tax_business_info, orders.user_id AS orders_user_id, orders.event_id AS orders_event_id, orders.marketer_id AS orders_marketer_id, orders.created_at AS orders_created_at, orders.completed_at AS orders_completed_at, orders.trashed_at AS orders_trashed_at, orders.transaction_id AS orders_transaction_id, orders.paid_via AS orders_paid_via, orders.payment_mode AS orders_payment_mode, orders.brand AS orders_brand, orders.exp_month AS orders_exp_month, orders.exp_year AS orders_exp_year, orders.last4 AS orders_last4, orders.stripe_token AS orders_stripe_token, orders.paypal_token AS orders_paypal_token, orders.status AS orders_status, orders.cancel_note AS orders_cancel_note, orders.order_notes AS orders_order_notes, orders.tickets_pdf_url AS orders_tickets_pdf_url, orders.discount_code_id AS orders_discount_code_id \nFROM orders \nWHERE %(param_1)s = orders.user_id'] [parameters: {'param_1': 1}]
127.0.0.1 - - [10/Feb/2019 16:08:56] "GET /v1/events?filter=%5B%7B%22name%22%3A%22state%22%2C%22op%22%3A%22eq%22%2C%22val%22%3A%22published%22%7D%2C%7B%22or%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222019-02-10T10%3A38%3A56.422Z%22%7D%2C%7B%22name%22%3A%22ends-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222019-02-10T10%3A38%3A56.422Z%22%7D%5D%7D%5D&include=event-topic%2Cevent-sub-topic%2Cevent-type%2Cspeakers-call&page%5Bnumber%5D=1&page%5Bsize%5D=6&sort=starts-at HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [10/Feb/2019 16:08:56] "GET /v1/events?filter=%5B%7B%22name%22%3A%22state%22%2C%22op%22%3A%22eq%22%2C%22val%22%3A%22published%22%7D%2C%7B%22or%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222019-02-10T10%3A38%3A56.422Z%22%7D%2C%7B%22name%22%3A%22ends-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222019-02-10T10%3A38%3A56.422Z%22%7D%5D%7D%5D&include=event-topic%2Cevent-sub-topic%2Cevent-type%2Cspeakers-call&page%5Bnumber%5D=1&page%5Bsize%5D=6&sort=starts-at HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/anupam/github/open-event-server/app/__init__.py", line 67, in __call__
    return self.app(environ, start_response)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/home/anupam/github/open-event-server/app/api/helpers/permission_manager.py", line 439, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/home/anupam/github/open-event-server/app/api/helpers/permission_manager.py", line 286, in create_event
    return view(*view_args, **view_kwargs)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/home/anupam/github/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 155, in get
    result = schema.dump(objects).data
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 511, in dump
    **kwargs
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 124, in serialize
    for idx, d in enumerate(obj)]
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 124, in <listcomp>
    for idx, d in enumerate(obj)]
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 147, in serialize
    index=(index if index_errors else None)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 141, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 243, in serialize
    value = self.get_value(attr, obj, accessor=accessor)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 186, in get_value
    return accessor_func(check_key, obj, default)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 402, in get_attribute
    return utils.get_value(attr, obj, default)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/utils.py", line 306, in get_value
    return _get_value_for_keys(key.split('.'), obj, default)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/utils.py", line 311, in _get_value_for_keys
    return _get_value_for_key(keys[0], obj, default)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/marshmallow/utils.py", line 322, in _get_value_for_key
    attr = getattr(obj, key)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 557, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
    
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 635, in _emit_lazyload
    result = q.all()
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/anupam/github/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column orders.company does not exist
LINE 1: ...orders_country, orders.zipcode AS orders_zipcode, orders.com...
                                                             ^
 [SQL: 'SELECT orders.deleted_at AS orders_deleted_at, orders.id AS orders_id, orders.identifier AS orders_identifier, orders.amount AS orders_amount, orders.address AS orders_address, orders.city AS orders_city, orders.state AS orders_state, orders.country AS orders_country, orders.zipcode AS orders_zipcode, orders.company AS orders_company, orders.tax_business_info AS orders_tax_business_info, orders.user_id AS orders_user_id, orders.event_id AS orders_event_id, orders.marketer_id AS orders_marketer_id, orders.created_at AS orders_created_at, orders.completed_at AS orders_completed_at, orders.trashed_at AS orders_trashed_at, orders.transaction_id AS orders_transaction_id, orders.paid_via AS orders_paid_via, orders.payment_mode AS orders_payment_mode, orders.brand AS orders_brand, orders.exp_month AS orders_exp_month, orders.exp_year AS orders_exp_year, orders.last4 AS orders_last4, orders.stripe_token AS orders_stripe_token, orders.paypal_token AS orders_paypal_token, orders.status AS orders_status, orders.cancel_note AS orders_cancel_note, orders.order_notes AS orders_order_notes, orders.tickets_pdf_url AS orders_tickets_pdf_url, orders.discount_code_id AS orders_discount_code_id \nFROM orders \nWHERE %(param_1)s = orders.event_id'] [parameters: {'param_1': 1}]
```

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 looks like I didn't migrated the db on the server after rebasing. Doing it fixed it. Closing the issue.
