### ISSUE TITLE
Error after logging in

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3262]
Logged in my account, visited home page and this

Environment: production

```
TypeError: Cannot read property 'query' of null
    at n.<anonymous> (/fastboot/app/assets/open-event-frontend-173e8c768e51500fb3d6967c711323e8.js:1977:52)
    at E (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:1039:147)
    at Generator._invoke (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:1037:7)
    at Generator.e.(anonymous function) [as next] (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:1039:326)
    at a (/fastboot/app/assets/open-event-frontend-173e8c768e51500fb3d6967c711323e8.js:1968:269)
    at o (/fastboot/app/assets/open-event-frontend-173e8c768e51500fb3d6967c711323e8.js:1970:15)
    at /fastboot/app/assets/open-event-frontend-173e8c768e51500fb3d6967c711323e8.js:1970:74
    at new P (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:841:5)
    at n.<anonymous> (/fastboot/app/assets/open-event-frontend-173e8c768e51500fb3d6967c711323e8.js:1969:8)
    at n.Ember.Route.extend.model (/fastboot/app/assets/open-event-frontend-173e8c768e51500fb3d6967c711323e8.js:1984:68)
    at n [as model] (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:3200:9)
    at n.a.deserialize (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:2731:131)
    at t.getModel (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:5081:26)
    at /fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:5061:215
    at y (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:5237:17)
    at S (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:5247:12)
    at x (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:5245:128)
    at t.invokeWithOnError (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4776:242)
    at e.t.flush (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4768:74)
    at e.t.flush (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4781:358)
    at e.n._end (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4843:9)
    at _boundAutorunEnd (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4793:574)
    at a (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:832:61)
    at /fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:832:206
    at l (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:526:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by CosmicCoder96** [comment]
@niranjan94 In such scenarios, fastboot often bypasses the default error handlers of the app, I assume something is wrong with the production configuration, can you please take a look?

**Comment by iamareebjamal** [comment]
Is this not released yet?

**Comment by kushthedude** [comment]
It has been released .

**Comment by iamareebjamal** [comment]
It is still happening

**Comment by kushthedude** [comment]
@CosmicCoder96

**Comment by shreyanshdwivedi** [comment]
Closed in favor of https://github.com/fossasia/open-event-frontend/pull/3412
Open it if faced again
