### ISSUE TITLE
Error message after accepting a role-invite 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#3347]
I saw there was a similar bug but with different error message https://github.com/fossasia/open-event-frontend/issues/2771

**Describe the bug**
After accepting an co-organizer role invitation, the following message showed up. However, the acceptance worked. I was able to access the event page. 

![Screenshot from 2019-08-02 09-32-20](https://user-images.githubusercontent.com/1658742/62353190-56149280-b50a-11e9-9cf7-1613ee42b332.png)

**Desktop**
 - OS: Ubuntu 18.04.1
 - Browser: Chrome

**Comment by kushthedude** [comment]
Taking a look on it

**Comment by mariobehling** [comment]
This bug still exists. Getting error message as follows on live system:

Error: TransitionAborted
    at s (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:3396:35)
    at y (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:5237:17)
    at S (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:5247:12)
    at x (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:5245:128)
    at E (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:5243:136)
    at t.invokeWithOnError (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:4776:242)
    at e.t.flush (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:4768:74)
    at e.t.flush (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:4781:358)
    at e.n._end (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:4843:9)
    at _boundAutorunEnd (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:4793:574)
    at a (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:832:61)
    at /fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:832:206
    at u (/fastboot/app/assets/vendor-5c235d65fc9a43607a9ca6638b92fa57.js:526:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by iamareebjamal** [comment]
This needs to be fixed on priority @kushthedude @mrsaicharan1

**Comment by kushthedude** [comment]
@iamareebjamal I think this might have been fixed with the user redirection PR, if it is still present I will check into it.

**Comment by iamareebjamal** [comment]
Yes, you're correct. Please see if it is still present

**Comment by kushthedude** [comment]
> Yes, you're correct. Please see if it is still present

Still present! But there is a new bug too, I will be opening an issue to address it.

**Comment by iamareebjamal** [comment]
Status?
