### ISSUE TITLE
Event Page shows error in fastboot mode

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4018]
And then loads correctly in client.

Error:

```
Error while processing route: public.index Using createRecord in Fastboot requires you to add the "crypto" package to "fastbootDependencies" in your package.json Error: Using createRecord in Fastboot requires you to add the "crypto" package to "fastbootDependencies" in your package.json
    at Object.getRandomValues (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:10566:139)
    at ae (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:10571:52)
    at e.he [as _generate] (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:10575:44)
    at e.t.createIdentifierForNewRecord (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:10582:376)
    at e.t._build (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:10623:12)
    at e.t.build (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:10621:124)

```

**Comment by kushthedude** [comment]
Solved ?
