### ISSUE TITLE
Remove deprecation `ember-data:evented-api-usage`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#4024]
Due to the following depreciation, it is very hard to read the travis logs. For every single test there are 10-15 depreciation of id `ember-data:evented-api-usage`

```sh
 WARN: DEPRECATION: Called ready on event#39ae7368 [deprecation id: ember-data:evented-api-usage] See https://deprecations.emberjs.com/ember-data/v3.x/#deprecatingrecordlifecycleeventmethods for more details.
3950                    at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:59858:21)
3951                    at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:59956:9)
3952                    at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:59885:9)
3953                    at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:59956:9)
3954                    at handleDeprecationWorkflow (http://localhost:7357/assets/vendor.js:88577:9)
3955                    at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:59956:9)
3956                    at deprecationCollector (http://localhost:7357/assets/vendor.js:88602:5)
3957                    at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:59956:9)
3958                    at invoke (http://localhost:7357/assets/vendor.js:59968:9)
```

**Comment by adrijshikhar** [comment]
@kushthedude i would like to work on this issue, can you help me out?

**Comment by mariobehling** [comment]
Will not be an issue in next version of project. Therefore closing it.
