### ISSUE TITLE
Error Message on accessing events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8457]
After not using the app for some time and loggin in again there is an error message.

![Screenshot from 2022-03-25 10-00-35](https://user-images.githubusercontent.com/1583873/160089504-7e323510-c112-47cd-90e2-d4b6f7343e98.png)

Failed to load resource: the server responded with a status of 404 ()
api.eventyay.com/v1/events/2764/event-copyright:1          Failed to load resource: the server responded with a status of 404 ()
state-machine.js:86 Sentry Logger [Error]: t: `beforeSend` returned `null`, will not send event.
    at new t (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:21433:67)
    at https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:21482:89
    at Array.<anonymous> (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19197:72)
    at https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19195:63
    at Array.forEach (<anonymous>)
    at e._executeHandlers (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19195:18)
    at https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19197:161
    at new e (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19196:5)
    at e.then (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19197:8)
    at t.e._processEvent (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:21482:21)
    at t.e._captureEvent (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:21474:211)
    at https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:21448:91
    at Array.<anonymous> (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19197:72)
    at https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19195:63
    at Array.forEach (<anonymous>)
    at e._executeHandlers (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19195:18)
    at https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19197:161
    at new e (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19196:5)
    at e.then (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19197:8)
    at t.e.captureException (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:21448:65)
    at e._invokeClient (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19180:19)
    at e.captureException (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:19156:120)
    at _Ember.onerror (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:21823:63)
    at t.invokeWithOnError (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:5117:262)
    at e.t.flush (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:5109:74)
    at e.t.flush (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:5123:207)
    at e.n._end (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:5185:9)
    at e.n.end (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:5140:230)
    at e.n._run (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:5187:70)
    at e.n._join (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:5186:246)
    at e.n.join (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:5151:13)
    at Function.d [as join] (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:3729:28)
    at n.f.error (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:10773:11)
    at u (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:175:118)
    at Object.fireWith [as rejectWith] (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:176:694)
    at S (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:458:468)
    at XMLHttpRequest.<anonymous> (https://eventyay.com/assets/vendor-b49f931875b2231b2273991f79229c32.js:469:206)
(anonymous) @ state-machine.js:86
api.eventyay.com/v1/events/2764/group:1          Failed to load resource: the server responded with a status of 500 ()

**Comment by progmatic-99** [comment]
Not able to reproduce this.
