### ISSUE TITLE
Fix error message on event pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9035]
After refresh or newly accessing an event page often an error message appears "An Error has ocurred". For the user there is not error visible and there is no action that the user needs to do. A refresh of the page does not show the error again.

The console shows the following
**Error 1:**
![Screenshot from 2023-08-02 22-30-28](https://github.com/fossasia/open-event-frontend/assets/1583873/9ce2d409-7561-4160-86d6-c976cefdfef2)
https://api.eventyay.com/v1/events/3171/tax
`{"errors": [{"status": 404, "source": {"parameter": "event_id"}, "title": "Object not found", "detail": "Tax: 3171 not found"}], "jsonapi": {"version": "1.0"}}`

**Error 2:**
![Screenshot from 2023-08-02 22-35-22](https://github.com/fossasia/open-event-frontend/assets/1583873/4c6ac67a-d82c-4078-a3a6-edbc2b1ba4ef)
https://api.eventyay.com/v1/events/3171/video-stream
`{"errors": [{"status": 404, "source": {"parameter": "id"}, "title": "Object not found", "detail": "Video Stream: 687 not found"}], "jsonapi": {"version": "1.0"}}`

**Error 3 and more errors:**
![Screenshot from 2023-08-02 22-36-41](https://github.com/fossasia/open-event-frontend/assets/1583873/aa7c1aa3-b5dc-4d6f-8bef-d00620c61b44)
`state-machine.js:86 Sentry Logger [error]: t: `beforeSend` returned `null`, will not send event.
    at new t (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22399:67)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22448:89
    at Array.<anonymous> (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:72)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20081:63
    at Array.forEach (<anonymous>)
    at e._executeHandlers (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20081:18)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:161
    at new e (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20082:5)
    at e.then (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:8)
    at e._processEvent (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22448:21)
    at e._captureEvent (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22440:211)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22414:91
    at Array.<anonymous> (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:72)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20081:63
    at Array.forEach (<anonymous>)
    at e._executeHandlers (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20081:18)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:161
    at new e (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20082:5)
    at e.then (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:8)
    at e.captureException (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22414:65)
    at e._invokeClient (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20066:19)
    at e.captureException (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20042:120)
    at _Ember.onerror (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22809:63)
    at t.invokeWithOnError (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5117:262)
    at t.flush (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5109:74)
    at t.flush (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5123:207)
    at n._end (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5185:9)
    at n.end (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5140:230)
    at n._run (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5187:70)
    at n._join (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5186:246)
    at n.join (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5151:13)
    at Function.p [as join] (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:3729:28)
    at d.error (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:10963:11)
    at c (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:175:118)
    at Object.fireWith [as rejectWith] (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:176:694)
    at w (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:458:468)
    at XMLHttpRequest.<anonymous> (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:469:206)
(anonymous) @ state-machine.js:86
api.eventyay.com/v1/events/3171/event-copyright:1     Failed to load resource: the server responded with a status of 404 ()
state-machine.js:86 Sentry Logger [log]: Adding outcome: error:before_send
state-machine.js:86 Sentry Logger [error]: t: `beforeSend` returned `null`, will not send event.
    at new t (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22399:67)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22448:89
    at Array.<anonymous> (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:72)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20081:63
    at Array.forEach (<anonymous>)
    at e._executeHandlers (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20081:18)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:161
    at new e (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20082:5)
    at e.then (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:8)
    at e._processEvent (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22448:21)
    at e._captureEvent (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22440:211)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22414:91
    at Array.<anonymous> (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:72)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20081:63
    at Array.forEach (<anonymous>)
    at e._executeHandlers (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20081:18)
    at https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:161
    at new e (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20082:5)
    at e.then (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20083:8)
    at e.captureException (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22414:65)
    at e._invokeClient (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20066:19)
    at e.captureException (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:20042:120)
    at _Ember.onerror (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:22809:63)
    at t.invokeWithOnError (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5117:262)
    at t.flush (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5109:74)
    at t.flush (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5123:207)
    at n._end (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5185:9)
    at n.end (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5140:230)
    at n._run (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5187:70)
    at n._join (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5186:246)
    at n.join (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:5151:13)
    at Function.p [as join] (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:3729:28)
    at d.error (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:10963:11)
    at c (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:175:118)
    at Object.fireWith [as rejectWith] (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:176:694)
    at w (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:458:468)
    at XMLHttpRequest.<anonymous> (https://eventyay.com/assets/vendor-abeed9d5d54cbe6ee8ca96ca1c32a262.js:469:206)
(anonymous) @ state-machine.js:86
api.eventyay.com/v1/events/3171/group:1     Failed to load resource: the server responded with a status of 401 ()
state-machine.js:86 `

**Comment by manzil-infinity180** [comment]
is this issue open?

**Comment by Riya10jain** [comment]
Hi! I’m a 3rd year engineering student and a beginner open-source contributor.

I noticed this issue is still open and I’d love to work on it if it’s not currently being handled.
Could you please confirm whether I can take this up and guide me on the expected approach?

Thank you!
